# Define inputs for the workflow.
inputs:
  - name: reference_data
    metadata: https://data.nextstrain.org/files/ncov/open/reference/metadata.tsv.xz
    aligned: https://data.nextstrain.org/files/ncov/open/reference/aligned.fasta.xz
  - name: mycustom_data
    metadata: data/mycustom_metadata.tsv
    sequences: data/mycustom_sequences.fasta

refine:
  root: "Wuhan-Hu-1/2019"
  
builds:
  only_custom:
    title: "Only my custom data build"
    subsampling_scheme: custom_scheme
    
subsampling:
  custom_scheme:
    custom_sample:
      query: --query "(mycustom_data == 'yes')"
